kind: pipeline
name: Batik Recovery

environment:
  VENDOR: xiaomi
  DEVICE: pine


steps:
- name: envlunch
  image: fr3akyphantom/droid-builder:latest
  environment:
    GIT_NAME:
      from_secret : GIT_NAME
    BR_BRANCH:
       from_secret : BR_BRANCH
    TOKEN:
      from_secret : TELEGRAM_TOKEN
    CHAT_ID:
      from_secret : CHANNEL_ID
    OWNER_ID:
      from_secret : COWNER_ID
    STATUS:
      from_secret : STATUS
  commands:
  - wget -q https://github.com/rzlamrr/scripts/raw/master/private/envlunch.sh
  - bash envlunch.sh
- name: sync
  image: fr3akyphantom/droid-builder:latest
  environment:
    GIT_NAME:
      from_secret : GIT_NAME
    BR_BRANCH:
       from_secret : BR_BRANCH
    TOKEN:
      from_secret : TELEGRAM_TOKEN
    CHAT_ID:
      from_secret : CHANNEL_ID
    OWNER_ID:
      from_secret : COWNER_ID
    STATUS:
      from_secret : STATUS
  environment:
    VENDOR: xiaomi
    DEVICE: pine
  commands:
  - wget -q https://github.com/rzlamrr/scripts/raw/master/private/make.sh
  - bash make.sh
- name: telegram
  image: appleboy/drone-telegram
  secrets:
    - source: CHAT_ID
      target: drone-telegram_token
    - source: TELEGRAM_TOKEN
      target: drone-telegram_to
  settings:
    format: markdown
    message: >
      {{#success build.status}}
      #twrp #batik #pine #unofficial
      **🆕 <b>Batik recovery</b> build is succeeded!**

      📱 Device: 

      ⚒ Commit: ```{{commit.message}}``` 🧑‍💻 _{{commit.author}}_

      ✨ Completed in {{since build.started}}
    document:
      - $(find $(pwd)/out/target/product/${DEVICE}/*pine*.zip 2>/dev/null)
- name: fail
  image: appleboy/drone-telegram
  secrets:
    - source: CHAT_ID
      target: drone-telegram_token
    - source: TELEGRAM_TOKEN
      target: drone-telegram_to
  settings:
    format: markdown
    message: >
      {{#failure build.status}}
      Build Batik Recovery for pine
      ⚒ Commit: ```{{commit.message}}``` 🧑‍💻 _{{commit.author}}_
      ❗️ Errors in {{since build.started}}
    document:
      - $(find $(pwd)/${product}-${DEVICE}.log 2>/dev/null)
